# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(791, 557)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 771, 541))
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.main0 = QtWidgets.QWidget()
        self.main0.setObjectName("main0")
        self.titleEdit = QtWidgets.QLineEdit(self.main0)
        self.titleEdit.setGeometry(QtCore.QRect(230, 60, 341, 71))
        font = QtGui.QFont()
        font.setFamily("HY중고딕")
        font.setPointSize(32)
        self.titleEdit.setFont(font)
        self.titleEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.titleEdit.setObjectName("titleEdit")
        self.btnGraph = QtWidgets.QPushButton(self.main0)
        self.btnGraph.setGeometry(QtCore.QRect(330, 200, 131, 51))
        self.btnGraph.setObjectName("btnGraph")
        self.btnExit = QtWidgets.QPushButton(self.main0)
        self.btnExit.setGeometry(QtCore.QRect(330, 360, 131, 51))
        self.btnExit.setObjectName("btnExit")
        self.label = QtWidgets.QLabel(self.main0)
        self.label.setGeometry(QtCore.QRect(600, 10, 191, 201))
        self.label.setStyleSheet("image: url(:/newPrefix/img1.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.main0)
        self.frame.setGeometry(QtCore.QRect(-10, -10, 791, 531))
        self.frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.titleEdit.raise_()
        self.btnGraph.raise_()
        self.btnExit.raise_()
        self.label.raise_()
        self.stackedWidget.addWidget(self.main0)
        self.graph1 = QtWidgets.QWidget()
        self.graph1.setObjectName("graph1")
        self.GraphTitle = QtWidgets.QLabel(self.graph1)
        self.GraphTitle.setGeometry(QtCore.QRect(240, 10, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.GraphTitle.setFont(font)
        self.GraphTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.GraphTitle.setObjectName("GraphTitle")
        self.graphWidget = QtWidgets.QWidget(self.graph1)
        self.graphWidget.setGeometry(QtCore.QRect(30, 60, 601, 451))
        self.graphWidget.setObjectName("graphWidget")
        self.btnEnit = QtWidgets.QPushButton(self.graph1)
        self.btnEnit.setGeometry(QtCore.QRect(664, 62, 91, 71))
        self.btnEnit.setObjectName("btnEnit")
        self.btnBackGraph = QtWidgets.QPushButton(self.graph1)
        self.btnBackGraph.setGeometry(QtCore.QRect(660, 440, 91, 61))
        self.btnBackGraph.setObjectName("btnBackGraph")
        self.stackedWidget.addWidget(self.graph1)
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.stackedWidget.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titleEdit.setText(_translate("MainWindow", "파충류 사육장"))
        self.btnGraph.setText(_translate("MainWindow", "실시간 그래프"))
        self.btnExit.setText(_translate("MainWindow", "나가기"))
        self.GraphTitle.setText(_translate("MainWindow", "실시간 그래프"))
        self.btnEnit.setText(_translate("MainWindow", "그래프초기화"))
        self.btnBackGraph.setText(_translate("MainWindow", "나가기"))
import imgtest_rc
